apiVersion: v1
kind: Service
metadata:
  name: alert-webhook
  namespace: alertdemo
  labels:
    app: alert-webhook
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: alert-webhook
